export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_COUNTER_BY_VALUE = 'INCREASE_COUNTER_BY_VALUE';
export const DECREASE_COUNTER_BY_VALUE = 'DECREASE_COUNTER_BY_VALUE';
export const ADD_USER = 'ADD_USER';
